### PR TITLE
Add an option to run boostdep on a different boost directory

### PR DESCRIPTION
**Pull request by Mike-Devel**
I don't know anything about boost documentation (and I'm not a native speaker), so that second commit probably has to be reworked - sorry.

### CODE REVIEW

**Comment by pdimov** [comment]
Let's make that `--boost-root`.

When not given, we should probably look at the environment variable `BOOST_ROOT` too.

**Comment by Mike-Devel** [comment]
Sounds reasonable. I should be able to take care of this sometime over the weekend. 

Do I need to manually edit the docu html file too or is that auto-generated by some tool?

**Comment by pdimov** [comment]
It's generated by quickbook. I'll take care of it.

**Comment by Mike-Devel** [comment]
I made the changes - it became a bit more elaborate change than I expected, but I didn't find a more elegant solution to deal with all combinations, error cases and provide meaningfull message to the user.

Note: I only checked this on Windows with a recent version of VS2017 and Ubuntu 18.04 (wsl) with gcc 7.3, so no c++03 toolchains.

**Comment by Mike-Devel** [comment]
rebased onto develop

**Comment by pdimov** [comment]
Thanks, but what we have now is good enough.

**Comment by Mike-Devel** [comment]
Ah, somehow I overlooked your changes (also explains some of the merge conflicts I had during rebasing ;))

**Pull request closed without merging**
