### PR TITLE
allow blocking dependencies (because they are optional)

### PR DESCRIPTION
**Pull request by HDembinski**
Adds a cmdline option to exclude dependencies found during scanning. I can use this to block known optional dependencies.

### CODE REVIEW

**Comment by pdimov** [comment]
I think that this should be `--ignore` instead of `--block`.

**Comment by HDembinski** [comment]
Ok, but what do you use a shortcut then? `-I` is already taken.

**Comment by HDembinski** [comment]
Feel free to edit this as you like, if you are generally ok with this feature.

**Comment by pdimov** [comment]
`-N` should work.

**Comment by HDembinski** [comment]
Thinking about it more, I realized a flaw in this approach. The flag should only ignore primary dependencies. If the module enters through a secondary dependency, it should be kept.

**Comment by pdimov** [comment]
There are arguments both ways. You could very well wish to ignore a module that is an optional and unneeded dependency of one of your primary dependencies. So I'm inclined to think that this is correct as written. (If you want to keep a secondary dependency, you can just remove the `-N` option; but if the option only ignored primary dependencies, there would be no way to ignore a secondary dependency.)

**Comment by HDembinski** [comment]
My use case for this flag is basically to add a workaround, because depinst doesn't know about preprocessor flags. In my own library, I know that a dependency found by depinst is actually optional, but it will be difficult to figure that out for all the secondary libraries. And even so, the library way enter again at the third level. And so forth. I think ignoring a library completely is very brittle. Ignoring it at the primary level is not and solves my problem.

**Comment by HDembinski** [comment]
Besides, the implementation is much easier now.

**Comment by HDembinski** [comment]
thanks!

**Pull request merged**
